# Site settings
title: Mike Seid
email: mbseid@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My little space on the large internet
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog.seid.io" # the base hostname & protocol for your site
twitter_username: mbseid
github_username:  mbseid

# Build settings
markdown: kramdown
highlighter: rouge
